# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View


default:
  http_metas:
    content-type: text/html

  metas:
    title:        Emploi du temps
    description:  Emploi du temps de l'ENSISA - IARISS
    keywords:     Emploi du temps, edt, IARISS, UHA, ENSISA
    language:     fr
    #robots:       index, follow

  stylesheets:    [base.css, modele07.css, dragndrop.css, ui-lightness/jquery-ui-1.8.13.custom.css  ]

  javascripts:
    - jsutils.js
    - jquery.js
    - jquery-ui.js
#     - ui/jquery.ui.core.js
#     - ui/jquery.ui.widget.js
#     - ui/jquery.ui.mouse.js
#     - ui/jquery.ui.sortable.js
#     - ui/jquery.ui.position.js
#     - ui/jquery.ui.droppable.js
#     - ui/jquery.ui.draggable.js

  has_layout:     true
  layout:         layout
