# Configuration:
#   columns:
#     identifier:   { type: string(255) }
#     project_id:         { type: string(255) }
#       'displayMode' => '1057855',
#       'displayConfId' => '8',

Filiere:
  columns:
    url:                { type: string(255) }
    nom:                { type: string(255) }
    description:        { type: string(4000) }
    logo:               { type: string(255) }
    weight:             { type: integer, default: 0 }
    in_menu:            { type: boolean, default: false }
  relations:
    Promotions:  { class: Promotion, local: id, foreign: filiere_id, type: many }

Promotion:
  columns:
    url:                { type: string(255) }
    nom:                { type: string(255) }
    description:        { type: string(4000) }
    filiere_id:         { type: integer, notnull: true }
    weight:             { type: integer, default: 0 }
    in_menu:            { type: boolean, default: false }
    project_id:         { type: string(255), notnull: true }
    id_tree:            { type: string(255) }
    branch_id:          { type: string(255) }
    select_branch_id:   { type: string(255) }
    select_id:          { type: string(255) }
    id_piano_day:       { type: string(255), default: '0,1,2,3,4' }
    width:              { type: integer, default: 800 }
    height:             { type: integer, default: 600 }
  relations:
    Filiere:  { local: filiere_id, foreign: id, type: one }

sfGuardUserProfile:
  tableName:     sf_guard_user_profile
  columns:
    user_id:          { type: integer(20), notnull: true }
    first_name:       { type: string(30) }
    last_name:        { type: string(30) }
    facebook_uid:     { type: string(20) }
    email:            { type: string(255) }
    email_hash:       { type: string(255) }
  indexes:
    facebook_uid_index:
      fields: [facebook_uid]
      unique: true
    email_index:
      fields: [email]
      unique: true
    email_hash_index:
      fields: [email_hash]
      unique: true
  relations:
    sfGuardUser:
      type: one
      foreignType: one
      class: sfGuardUser
      local: user_id
      foreign: id
      onDelete: cascade
      foreignAlias: Profile
